# Generated by Django 4.0.1 on 2022-01-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=500)),
                ('public_key', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ETH',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=500)),
                ('public_key', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
